# Generated by Django 3.1 on 2020-11-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='housemate.property')),
            ],
            bases=('housemate.property',),
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='housemate.user')),
                ('ll_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='housemate.user')),
                ('rtb_id', models.IntegerField()),
            ],
            bases=('housemate.user',),
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='housemate.property')),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='housemate.property')),
                ('rent', models.IntegerField()),
            ],
            bases=('housemate.property',),
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='housemate.property')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='housemate.property')),
                ('price', models.IntegerField()),
            ],
            bases=('housemate.property',),
        ),
        migrations.CreateModel(
            name='ShareProperty',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='housemate.property')),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='housemate.property')),
                ('rent', models.IntegerField()),
                ('rent_type', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
            ],
            bases=('housemate.property',),
        ),
        migrations.CreateModel(
            name='ShareProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habits', models.CharField(max_length=150)),
                ('likes', models.CharField(max_length=150)),
                ('dislikes', models.CharField(max_length=150)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.user')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owner_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.user'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('P', 'Photos'), ('V', 'Videos'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('advt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.property'),
        ),
    ]
