# Generated by Django 3.1.3 on 2020-11-27 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traits', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtb_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ownername', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ShareProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('rent_type', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('shareID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.property')),
            ],
        ),
        migrations.CreateModel(
            name='ShareProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=150, null=True)),
                ('dislikes', models.CharField(max_length=150, null=True)),
                ('habits', models.ManyToManyField(to='housemate.Habits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.user')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('saleID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('rentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('P', 'Photos'), ('V', 'Videos'), ('O', 'Other')], max_length=1)),
                ('filename', models.FileField(upload_to='media/')),
                ('adv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='uname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.user'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='property_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.property'),
        ),
    ]
