# Generated by Django 3.1 on 2020-11-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='id',
            field=models.AutoField(auto_created=True, default=-1.0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
