# Generated by Django 3.1.3 on 2020-12-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemate', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareproperty',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='shareproperty',
            name='rent_type',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='rent_type',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='shareproperty',
            name='shareProfileID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.shareprofile'),
        ),
        migrations.AlterField(
            model_name='shareproperty',
            name='shareID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.rentalproperty'),
        ),
    ]
