# Generated by Django 3.1.3 on 2020-12-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemate', '0003_auto_20201213_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ownername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='housemate.landlord'),
        ),
    ]
